[package]
name = "cold"
version = "0.0.0"
authors = ["Vladislav Melnik <vladislav.melnik@protonmail.com>"]
edition = "2018"
description = "Rust runtime for p2p networking"
license = "MIT"
repository = "https://github.com/vlad9486/cold"

[dependencies]
futures = "0.3"

[features]
std = []
